name: Molecule Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix
      - name: Run Molecule Test
        if: github.event_name == 'pull_request'
        run: |
          cd ${{ github.workspace }}/${{ github.event.pull_request.head.repo.name }}
          for dir in ${{ inputs.directory-path }}/* ; do
            if [ -d "${dir}" ]; then
              cd "${dir}" && molecule test
            fi
          done
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
